## Лабораторная работа №2
### Вариант 3
Выполнил Данилов Максим

1. Изучение основ работы с массивами в NumPy:

Импорт библиотеки в программу

In [1]:
import numpy as np

Создание одномерных и многомерных массивов

In [2]:
# Одномерный массив (вектор) 
arr = np.array([1, 2, 3, 4, 5])
# Многомерный массив (матрица)
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

In [3]:
# Индексирование
element = arr[2] # Получение элемента с индексом 2
# Сложение и умножение
result_sum = arr + arr # Сложение 
result_product = arr * 2 # Умножение на скаляр
print(element)
print(result_sum)
print(result_product)

3
[ 2  4  6  8 10]
[ 2  4  6  8 10]


2. Решение задач на матричные операции

In [6]:
matrix_a = np.array([[1, 2], [3, 4]]) 
matrix_b = np.array([[5, 6], [7, 8]])
result_matrix = np.dot(matrix_a, matrix_b)
transposed_matrix = np.transpose(matrix_a)
print(result_matrix)
print(transposed_matrix)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [7]:
data = np.array([[1, 2, 3], [4, 5, 6]])
print(data)

[[1 2 3]
 [4 5 6]]


Практическое задание на работу с массивами и матричными операциями. • Создайте
два одномерных массива A и B, состоящих из 6 элементов каждый. Массив A должен содержать числа от 1 до 6, а массив B - числа от 7 до 12. • Вычислите среднее арифметическое элементов массивов A и B. • Вычислите стандартное отклонение элементов массивов A и B. • Выведите результаты статистических операций на экран.

In [15]:
A = np.arange(1,7)
B = np.arange(7,13)

In [16]:
A.mean()

3.5

In [17]:
A.std()

1.707825127659933

In [18]:
B.mean()

9.5

In [19]:
B.std()

1.707825127659933